import React, { useEffect, useState } from 'react'
import './App.css'
import axios from 'axios'
export const CurrencyConverter = () => {
    const [amount,setAmount]=useState(1)
    const [fromCountry,setFromCountry]=useState("INR")
    const [toCountry,setToCountry]=useState("USD")
    const [result,setResult]=useState(null)
    
    useEffect(()=>{
        const getdata = async () =>{
            try{
                let url =`https://api.exchangerate-api.com/v4/latest/${fromCountry}`
                const response = await axios.get(url)   
                setResult(amount*(response.data.rates[toCountry]))
            }
            catch(error){
                console.log("Error Fetching Api",error)
            }
        }
        getdata()
    })

  return (
    <div className="currencyconverter">
        <div className="currency-img">
            <img src="currency converter.png" alt="img" />
        </div>
        <div className="calcuator">
            <h3> <span>Currency</span> <span>Converter</span></h3>
            {/* Amount */}
            <label htmlFor="amount">Amount</label>
            <input type="number" name="amount" id="amount" value={amount} placeholder='Enter amount' onChange={(e)=>setAmount(e.target.value)}/>
            {/* from Country */}
            <label htmlFor="fromCurrency">From Currency</label>
            <select name="fromCurrency" id="fromCurrency" value={fromCountry} onChange={(e)=>setFromCountry(e.target.value)}>
                <option value="INR">India - INR</option>
                <option value="AED">United Arab Emirates - AED</option>
                <option value="AFN">Afghanistan - AFN</option>
                <option value="ALL">Albania - ALL</option>
                <option value="AMD">Armenia - AMD</option>
                <option value="ANG">Netherlands Antillean Guilder - ANG</option>
                <option value="AOA">Angola - AOA</option>
                <option value="ARS">Argentina - ARS</option>
                <option value="AUD">Australia - AUD</option>
                <option value="AWG">Aruba - AWG</option>
                <option value="AZN">Azerbaijan - AZN</option>
                <option value="BAM">Bosnia and Herzegovina - BAM</option>
                <option value="BBD">Barbados - BBD</option>
                <option value="BDT">Bangladesh - BDT</option>
                <option value="BGN">Bulgaria - BGN</option>
                <option value="BHD">Bahrain - BHD</option>
                <option value="BIF">Burundi - BIF</option>
                <option value="BMD">Bermuda - BMD</option>
                <option value="BND">Brunei Darussalam - BND</option>
                <option value="BOB">Bolivia - BOB</option>
                <option value="BRL">Brazil - BRL</option>
                <option value="BSD">Bahamas - BSD</option>
                <option value="BTN">Bhutan - BTN</option>
                <option value="BWP">Botswana - BWP</option>
                <option value="BYN">Belarus - BYN</option>
                <option value="BZD">Belize - BZD</option>
                <option value="CAD">Canada - CAD</option>
                <option value="CDF">Democratic Republic of the Congo - CDF</option>
                <option value="CHF">Switzerland - CHF</option>
                <option value="CLP">Chile - CLP</option>
                <option value="CNY">China - CNY</option>
                <option value="COP">Colombia - COP</option>
                <option value="CRC">Costa Rica - CRC</option>
                <option value="CUP">Cuba - CUP</option>
                <option value="CVE">Cape Verde - CVE</option>
                <option value="CZK">Czech Republic - CZK</option>
                <option value="DJF">Djibouti - DJF</option>
                <option value="DKK">Denmark - DKK</option>
                <option value="DOP">Dominican Republic - DOP</option>
                <option value="DZD">Algeria - DZD</option>
                <option value="EGP">Egypt - EGP</option>
                <option value="ERN">Eritrea - ERN</option>
                <option value="ETB">Ethiopia - ETB</option>
                <option value="EUR">Eurozone - EUR</option>
                <option value="FJD">Fiji - FJD</option>
                <option value="FKP">Falkland Islands - FKP</option>
                <option value="FOK">Faroe Islands - FOK</option>
                <option value="GBP">United Kingdom - GBP</option>
                <option value="GEL">Georgia - GEL</option>
                <option value="GGP">Guernsey - GGP</option>
                <option value="GHS">Ghana - GHS</option>
                <option value="GIP">Gibraltar - GIP</option>
                <option value="GMD">Gambia - GMD</option>
                <option value="GNF">Guinea - GNF</option>
                <option value="GTQ">Guatemala - GTQ</option>
                <option value="GYD">Guyana - GYD</option>
                <option value="HKD">Hong Kong - HKD</option>
                <option value="HNL">Honduras - HNL</option>
                <option value="HRK">Croatia - HRK</option>
                <option value="HTG">Haiti - HTG</option>
                <option value="HUF">Hungary - HUF</option>
                <option value="IDR">Indonesia - IDR</option>
                <option value="ILS">Israel - ILS</option>
                <option value="IMP">Isle of Man - IMP</option>
                <option value="IQD">Iraq - IQD</option>
                <option value="IRR">Iran - IRR</option>
                <option value="ISK">Iceland - ISK</option>
                <option value="JEP">Jersey - JEP</option>
                <option value="JMD">Jamaica - JMD</option>
                <option value="JOD">Jordan - JOD</option>
                <option value="JPY">Japan - JPY</option>
                <option value="KES">Kenya - KES</option>
                <option value="KGS">Kyrgyzstan - KGS</option>
                <option value="KHR">Cambodia - KHR</option>
                <option value="KID">Kiribati - KID</option>
                <option value="KMF">Comoros - KMF</option>
                <option value="KRW">South Korea - KRW</option>
                <option value="KWD">Kuwait - KWD</option>
                <option value="KYD">Cayman Islands - KYD</option>
                <option value="KZT">Kazakhstan - KZT</option>
                <option value="LAK">Laos - LAK</option>
                <option value="LBP">Lebanon - LBP</option>
                <option value="LKR">Sri Lanka - LKR</option>
                <option value="LRD">Liberia - LRD</option>
                <option value="LSL">Lesotho - LSL</option>
                <option value="LYD">Libya - LYD</option>
                <option value="MAD">Morocco - MAD</option>
                <option value="MDL">Moldova - MDL</option>
                <option value="MGA">Madagascar - MGA</option>
                <option value="MKD">North Macedonia - MKD</option>
                <option value="MMK">Myanmar - MMK</option>
                <option value="MNT">Mongolia - MNT</option>
                <option value="MOP">Macao - MOP</option>
                <option value="MRU">Mauritania - MRU</option>
                <option value="MUR">Mauritius - MUR</option>
                <option value="MVR">Maldives - MVR</option>
                <option value="MWK">Malawi - MWK</option>
                <option value="MXN">Mexico - MXN</option>
                <option value="MYR">Malaysia - MYR</option>
                <option value="MZN">Mozambique - MZN</option>
                <option value="NAD">Namibia - NAD</option>
                <option value="NGN">Nigeria - NGN</option>
                <option value="NIO">Nicaragua - NIO</option>
                <option value="NOK">Norway - NOK</option>
                <option value="NPR">Nepal - NPR</option>
                <option value="NZD">New Zealand - NZD</option>
                <option value="OMR">Oman - OMR</option>
                <option value="PAB">Panama - PAB</option>
                <option value="PEN">Peru - PEN</option>
                <option value="PGK">Papua New Guinea - PGK</option>
                <option value="PHP">Philippines - PHP</option>
                <option value="PKR">Pakistan - PKR</option>
                <option value="PLN">Poland - PLN</option>
                <option value="PYG">Paraguay - PYG</option>
                <option value="QAR">Qatar - QAR</option>
                <option value="RON">Romania - RON</option>
                <option value="RSD">Serbia - RSD</option>
                <option value="RUB">Russia - RUB</option>
                <option value="RWF">Rwanda - RWF</option>
                <option value="SAR">Saudi Arabia - SAR</option>
                <option value="SBD">Solomon Islands - SBD</option>
                <option value="SCR">Seychelles - SCR</option>
                <option value="SDG">Sudan - SDG</option>
                <option value="SEK">Sweden - SEK</option>
                <option value="SGD">Singapore - SGD</option>
                <option value="SHP">Saint Helena - SHP</option>
                <option value="SLE">Sierra Leone - SLE</option>
                <option value="SLL">Sierra Leone (deprecated) - SLL</option>
                <option value="SOS">Somalia - SOS</option>
                <option value="SRD">Suriname - SRD</option>
                <option value="SSP">South Sudan - SSP</option>
                <option value="STN">São Tomé and Príncipe - STN</option>
                <option value="SYP">Syria - SYP</option>
                <option value="SZL">Eswatini - SZL</option>
                <option value="THB">Thailand - THB</option>
                <option value="TJS">Tajikistan - TJS</option>
                <option value="TMT">Turkmenistan - TMT</option>
                <option value="TND">Tunisia - TND</option>
                <option value="TOP">Tonga - TOP</option>
                <option value="TRY">Turkey - TRY</option>
                <option value="TTD">Trinidad and Tobago - TTD</option>
                <option value="TVD">Tuvalu - TVD</option>
                <option value="TWD">Taiwan - TWD</option>
                <option value="TZS">Tanzania - TZS</option>
                <option value="UAH">Ukraine - UAH</option>
                <option value="UGX">Uganda - UGX</option>
                <option value="USD">United States - USD</option>
                <option value="UYU">Uruguay - UYU</option>
                <option value="UZS">Uzbekistan - UZS</option>
                <option value="VES">Venezuela - VES</option>
                <option value="VND">Vietnam - VND</option>
                <option value="VUV">Vanuatu - VUV</option>
                <option value="WST">Samoa - WST</option>
                <option value="XAF">Central African CFA franc - XAF</option>
                <option value="XCD">East Caribbean dollar - XCD</option>
                <option value="XDR">Special Drawing Rights - XDR</option>
                <option value="XOF">West African CFA franc - XOF</option>
                <option value="XPF">CFP franc - XPF</option>
                <option value="YER">Yemen - YER</option>
                <option value="ZAR">South Africa - ZAR</option>
                <option value="ZMW">Zambia - ZMW</option>
                <option value="ZWL">Zimbabwe - ZWL</option>
            </select>

            {/* to country */}
            <label htmlFor="toCurrency">To Currency</label>
            <select name='toCurrency' id="toCurrency" value={toCountry} onChange={(e)=>setToCountry(e.target.value)}>
                <option value="INR">India - INR</option>
                <option value="AED">United Arab Emirates - AED</option>
                <option value="AFN">Afghanistan - AFN</option>
                <option value="ALL">Albania - ALL</option>
                <option value="AMD">Armenia - AMD</option>
                <option value="ANG">Netherlands Antillean Guilder - ANG</option>
                <option value="AOA">Angola - AOA</option>
                <option value="ARS">Argentina - ARS</option>
                <option value="AUD">Australia - AUD</option>
                <option value="AWG">Aruba - AWG</option>
                <option value="AZN">Azerbaijan - AZN</option>
                <option value="BAM">Bosnia and Herzegovina - BAM</option>
                <option value="BBD">Barbados - BBD</option>
                <option value="BDT">Bangladesh - BDT</option>
                <option value="BGN">Bulgaria - BGN</option>
                <option value="BHD">Bahrain - BHD</option>
                <option value="BIF">Burundi - BIF</option>
                <option value="BMD">Bermuda - BMD</option>
                <option value="BND">Brunei Darussalam - BND</option>
                <option value="BOB">Bolivia - BOB</option>
                <option value="BRL">Brazil - BRL</option>
                <option value="BSD">Bahamas - BSD</option>
                <option value="BTN">Bhutan - BTN</option>
                <option value="BWP">Botswana - BWP</option>
                <option value="BYN">Belarus - BYN</option>
                <option value="BZD">Belize - BZD</option>
                <option value="CAD">Canada - CAD</option>
                <option value="CDF">Democratic Republic of the Congo - CDF</option>
                <option value="CHF">Switzerland - CHF</option>
                <option value="CLP">Chile - CLP</option>
                <option value="CNY">China - CNY</option>
                <option value="COP">Colombia - COP</option>
                <option value="CRC">Costa Rica - CRC</option>
                <option value="CUP">Cuba - CUP</option>
                <option value="CVE">Cape Verde - CVE</option>
                <option value="CZK">Czech Republic - CZK</option>
                <option value="DJF">Djibouti - DJF</option>
                <option value="DKK">Denmark - DKK</option>
                <option value="DOP">Dominican Republic - DOP</option>
                <option value="DZD">Algeria - DZD</option>
                <option value="EGP">Egypt - EGP</option>
                <option value="ERN">Eritrea - ERN</option>
                <option value="ETB">Ethiopia - ETB</option>
                <option value="EUR">Eurozone - EUR</option>
                <option value="FJD">Fiji - FJD</option>
                <option value="FKP">Falkland Islands - FKP</option>
                <option value="FOK">Faroe Islands - FOK</option>
                <option value="GBP">United Kingdom - GBP</option>
                <option value="GEL">Georgia - GEL</option>
                <option value="GGP">Guernsey - GGP</option>
                <option value="GHS">Ghana - GHS</option>
                <option value="GIP">Gibraltar - GIP</option>
                <option value="GMD">Gambia - GMD</option>
                <option value="GNF">Guinea - GNF</option>
                <option value="GTQ">Guatemala - GTQ</option>
                <option value="GYD">Guyana - GYD</option>
                <option value="HKD">Hong Kong - HKD</option>
                <option value="HNL">Honduras - HNL</option>
                <option value="HRK">Croatia - HRK</option>
                <option value="HTG">Haiti - HTG</option>
                <option value="HUF">Hungary - HUF</option>
                <option value="IDR">Indonesia - IDR</option>
                <option value="ILS">Israel - ILS</option>
                <option value="IMP">Isle of Man - IMP</option>
                <option value="IQD">Iraq - IQD</option>
                <option value="IRR">Iran - IRR</option>
                <option value="ISK">Iceland - ISK</option>
                <option value="JEP">Jersey - JEP</option>
                <option value="JMD">Jamaica - JMD</option>
                <option value="JOD">Jordan - JOD</option>
                <option value="JPY">Japan - JPY</option>
                <option value="KES">Kenya - KES</option>
                <option value="KGS">Kyrgyzstan - KGS</option>
                <option value="KHR">Cambodia - KHR</option>
                <option value="KID">Kiribati - KID</option>
                <option value="KMF">Comoros - KMF</option>
                <option value="KRW">South Korea - KRW</option>
                <option value="KWD">Kuwait - KWD</option>
                <option value="KYD">Cayman Islands - KYD</option>
                <option value="KZT">Kazakhstan - KZT</option>
                <option value="LAK">Laos - LAK</option>
                <option value="LBP">Lebanon - LBP</option>
                <option value="LKR">Sri Lanka - LKR</option>
                <option value="LRD">Liberia - LRD</option>
                <option value="LSL">Lesotho - LSL</option>
                <option value="LYD">Libya - LYD</option>
                <option value="MAD">Morocco - MAD</option>
                <option value="MDL">Moldova - MDL</option>
                <option value="MGA">Madagascar - MGA</option>
                <option value="MKD">North Macedonia - MKD</option>
                <option value="MMK">Myanmar - MMK</option>
                <option value="MNT">Mongolia - MNT</option>
                <option value="MOP">Macao - MOP</option>
                <option value="MRU">Mauritania - MRU</option>
                <option value="MUR">Mauritius - MUR</option>
                <option value="MVR">Maldives - MVR</option>
                <option value="MWK">Malawi - MWK</option>
                <option value="MXN">Mexico - MXN</option>
                <option value="MYR">Malaysia - MYR</option>
                <option value="MZN">Mozambique - MZN</option>
                <option value="NAD">Namibia - NAD</option>
                <option value="NGN">Nigeria - NGN</option>
                <option value="NIO">Nicaragua - NIO</option>
                <option value="NOK">Norway - NOK</option>
                <option value="NPR">Nepal - NPR</option>
                <option value="NZD">New Zealand - NZD</option>
                <option value="OMR">Oman - OMR</option>
                <option value="PAB">Panama - PAB</option>
                <option value="PEN">Peru - PEN</option>
                <option value="PGK">Papua New Guinea - PGK</option>
                <option value="PHP">Philippines - PHP</option>
                <option value="PKR">Pakistan - PKR</option>
                <option value="PLN">Poland - PLN</option>
                <option value="PYG">Paraguay - PYG</option>
                <option value="QAR">Qatar - QAR</option>
                <option value="RON">Romania - RON</option>
                <option value="RSD">Serbia - RSD</option>
                <option value="RUB">Russia - RUB</option>
                <option value="RWF">Rwanda - RWF</option>
                <option value="SAR">Saudi Arabia - SAR</option>
                <option value="SBD">Solomon Islands - SBD</option>
                <option value="SCR">Seychelles - SCR</option>
                <option value="SDG">Sudan - SDG</option>
                <option value="SEK">Sweden - SEK</option>
                <option value="SGD">Singapore - SGD</option>
                <option value="SHP">Saint Helena - SHP</option>
                <option value="SLE">Sierra Leone - SLE</option>
                <option value="SLL">Sierra Leone (deprecated) - SLL</option>
                <option value="SOS">Somalia - SOS</option>
                <option value="SRD">Suriname - SRD</option>
                <option value="SSP">South Sudan - SSP</option>
                <option value="STN">São Tomé and Príncipe - STN</option>
                <option value="SYP">Syria - SYP</option>
                <option value="SZL">Eswatini - SZL</option>
                <option value="THB">Thailand - THB</option>
                <option value="TJS">Tajikistan - TJS</option>
                <option value="TMT">Turkmenistan - TMT</option>
                <option value="TND">Tunisia - TND</option>
                <option value="TOP">Tonga - TOP</option>
                <option value="TRY">Turkey - TRY</option>
                <option value="TTD">Trinidad and Tobago - TTD</option>
                <option value="TVD">Tuvalu - TVD</option>
                <option value="TWD">Taiwan - TWD</option>
                <option value="TZS">Tanzania - TZS</option>
                <option value="UAH">Ukraine - UAH</option>
                <option value="UGX">Uganda - UGX</option>
                <option value="USD">United States - USD</option>
                <option value="UYU">Uruguay - UYU</option>
                <option value="UZS">Uzbekistan - UZS</option>
                <option value="VES">Venezuela - VES</option>
                <option value="VND">Vietnam - VND</option>
                <option value="VUV">Vanuatu - VUV</option>
                <option value="WST">Samoa - WST</option>
                <option value="XAF">Central African CFA franc - XAF</option>
                <option value="XCD">East Caribbean dollar - XCD</option>
                <option value="XDR">Special Drawing Rights - XDR</option>
                <option value="XOF">West African CFA franc - XOF</option>
                <option value="XPF">CFP franc - XPF</option>
                <option value="YER">Yemen - YER</option>
                <option value="ZAR">South Africa - ZAR</option>
                <option value="ZMW">Zambia - ZMW</option>
                <option value="ZWL">Zimbabwe - ZWL</option>
            </select>
            <p className='result'>{amount} {fromCountry} equal to {result} {toCountry}</p>
        </div>
    </div>
  )
}
